### ISSUE TITLE
Changelog updates missing

### ISSUE THREAD

**Issue by rclark** [mapbox/cfn-config#128]
@emilymcafee @xrwang could you please update the changelog for versions 2.3.0 and 2.4.0?

Thanks!

**Comment by emilymcafee** [comment]
Oops, yeah. 2.3.0 was https://github.com/mapbox/cfn-config/pull/123 - will add now.

**Comment by rclark** [comment]
@xrwang @yhahn @aarthykc could you please update the changelog for versions 2.5.0, 2.6.0, 2.6.1.

**Comment by emilymcafee** [comment]
These are on [the changelog](https://github.com/mapbox/cfn-config/blob/master/CHANGELOG.md#change-log), right?

**Comment by rclark** [comment]
Thanks, I'm a mess apparently.
