### ISSUE TITLE
[question] .skipConfirmTemplate if there's no template diff?

### ISSUE THREAD

**Issue by rclark** [mapbox/cfn-config#148]
https://github.com/mapbox/cfn-config/blob/72dcb36e069a62deadff2f0a8a66515f886afa46/lib/commands.js#L372-L379

In the `confirmTemplate` action, if there is no difference between the old and the new template, we just move on to the next step.

Compare that to the `confirmParameters` action, where if there is no difference between old and new parameters, we set `context.skipConfirmParameters = true` and then move on to the next step.

https://github.com/mapbox/cfn-config/blob/72dcb36e069a62deadff2f0a8a66515f886afa46/lib/commands.js#L361-L364

This becomes important when it comes time to run the `confirmChangeset` action. Here, the user is not prompted if `context.skipConfirmParameters` and `context.skipConfirmTemplate` are both true.

https://github.com/mapbox/cfn-config/blob/72dcb36e069a62deadff2f0a8a66515f886afa46/lib/commands.js#L448

@vsmart @kellyoung I'm wondering if this is an oversight? It seems to me that you could end up in a situation where there were no parameter changes, no template changes, and still the user is asked to confirm what's likely an empty changeset. 

Do you think we should be setting the `.skipConfirmTemplate` flag if there's no template diff?

**Comment by vsmart** [comment]
I can't think of any reason why this would be intentional. I agree that it's probably an oversight and we should set it, just like the `skipConfirmParameters` flag.

**Comment by rclark** [comment]
Thanks -- changed this in #149
