### ISSUE TITLE
template body can be too large

### ISSUE THREAD

**Issue by willwhite** [mapbox/cfn-config#16]
Working with a very large template will return this:

```
'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200
```

**Comment by gilzellner** [comment]
the issue is still there. what I do now is after the dynamic changes i make, i save the template to /tmp and then upload to s3. this is indeed quite silly, yet works.

**Comment by freenerd** [comment]
@gilzellner we upload the template to S3, see https://github.com/mapbox/cfn-config/blob/3d013020d809171afb953943bbd069bd07635fe2/index.js#L435-L465

**Comment by gilzellner** [comment]
hi, yes, I know, I do the same. I was just saying that the limitation on size still exists. By the way I would have expected for this to be taken care by abstraction on the side of AWS-SDK

**Comment by freenerd** [comment]
Ah okay, yes. The limit is [460,800 bytes](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html) when uploaded to S3.
