### ISSUE TITLE
NoEcho parameters get replaced with ****

### ISSUE THREAD

**Issue by danmactough** [mapbox/cfn-config#177]
This is very similar behavior to #26, but a lot has changed since that issue was opened and resolved in 2014. 😄

### Background

I have a template with multiple parameters, some of which have the `NoEcho` property set to `true`. These are secrets (like API keys) that I want stored in Secrets Manager. I do not want their values to be KMS encrypted.

### Details

Creating a stack works as expected (although the secrets get saved in plaintext in the saved configuration on S3).

When I update the stack, any NoEcho parameters **_that I accept the previous value for_** (whether using the prompt or using `-f`) have their value changed to the literal string `****`, which is the mask that CloudFormation uses to hide values for NoEcho parameters. This happens because we [fetch the previous values using a DescribeStacks call to CloudFormation](https://github.com/mapbox/cfn-config/blob/0cc06b5fadaf2c669874f07db04d4d62edfc538d/lib/lookup.js#L53), which only returns those masked values.

I want to be able to update a stack without needing to provide the values for every NoEcho parameter.

Here is a sample template that can be used to reproduce the behavior:

```json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "Example to demonstrate NoEcho parameter bug",
  "Parameters": {
    "DeploymentType": {
      "Type": "String",
      "Default": "staging",
      "AllowedValues": ["staging", "production", "dev"],
      "Description": "Is this a staging, production, or dev deployment"
    },
    "NotSecret": {
      "Type": "String",
      "Description": "This value is not secret"
    },
    "Secret": {
      "Type": "String",
      "NoEcho": true,
      "Description": "[secure] This value is secret"
    }
  },
  "Resources": {
    "SecretsManagerSecret": {
      "Type": "AWS::SecretsManager::Secret",
      "Properties": {
        "Name": {
          "Fn::Sub": "${DeploymentType}/cfn-config-noecho-parameter-bug"
        },
        "Description": "Example to demonstrate NoEcho parameter bug",
        "SecretString": {
          "Fn::Sub": "{ \"NotSecret\": \"${NotSecret}\", \"Secret\": \"${Secret}\" }"
        }
      }
    }
  }
}
```

To see the behavior:

1. Create the stack
2. Verify the value for `Secret` is stored correctly in Secrets Manager
3. Update the stack to change the `NotSecret` parameter but **NOT** the `Secret` parameter
4. Verify the value for `Secret` in Secrets Manager has been changed to `****`

cc @rclark

**Comment by rclark** [comment]
We look up the prior values so that the prompt can show you what you'll be accepting if you don't input anything. In the case of `NoEcho` (and arguably in every case where the user did not provide a non-default value), the `UpdateStack` API should use the `UsePreviousValue: true` flag instead of providing the looked-up value as a "new" value.
