### ISSUE TITLE
3.0.0 Breaks Integration

### ISSUE THREAD

**Issue by ingalls** [mapbox/cfn-config#180]
### Context

The  [NoEcho PR](https://github.com/mapbox/cfn-config/pull/178/files) seems to have an undesired side-effect in our current deploy flow.

Tl;Dr: Passing a new `GitSha` override parameter to the `update` function fails to update the stack, resulting in:

```
Update failed: Status: UNAVAILABLE | Reason: The submitted information didn't contain changes. Submit different information to create a change set. | Cannot execute changeset
```

despite the fact that the `GitSha` override is a new GitSha.

### Debugging

I pass an overrides object to cfn-config [here](https://github.com/mapbox/cfn-config/blob/master/lib/commands.js#L120) which contains the GitSha
```
{ parameters: { GitSha: '597b9cb48afffc4c072c4b0d5443847c02f070af' } }
```
I see the new GitSha in the CLI prompt as expected. However since the overridden parameter are set in the oldParameters as well as the newParameters, the [changesetParameters function](https://github.com/mapbox/cfn-config/blob/master/lib/commands.js#L847) does an equality check and assigns the `UsePreviousValue: true` property.

Contents of https://github.com/mapbox/cfn-config/blob/master/lib/commands.js#L518
```
[
  { ParameterKey: 'GitSha', UsePreviousValue: true },
  { ParameterKey: 'MapboxToken', UsePreviousValue: true },
  { ParameterKey: 'Bucket', UsePreviousValue: true },
  { ParameterKey: 'Branch', UsePreviousValue: true },
  { ParameterKey: 'DatabaseType', UsePreviousValue: true },
  { ParameterKey: 'DatabasePassword', UsePreviousValue: true },
  { ParameterKey: 'SSLCertificateIdentifier', UsePreviousValue: true },
  { ParameterKey: 'SharedSecret', UsePreviousValue: true },
  { ParameterKey: 'GithubSecret', UsePreviousValue: true },
  { ParameterKey: 'Project', UsePreviousValue: true },
  { ParameterKey: 'Owner', UsePreviousValue: true }
]
```

cc/ @rclark  @danmactough

**Comment by rclark** [comment]
Hi Nick! 

See discussion here https://github.com/mapbox/cfn-config/pull/178/files#r463129638. What got overlooked or is tripping up your integration?

```
When (context.overrides.force || context.overrides.skipPromptParameters) is false, we DO assign the overrideParameters to context.oldParameters. Then in confirmParameters, context.oldParameters has the expected values when the diff is performed.
```

The intentions of these two boolean flags are (I believe):

- **context.overrides.force**: Skip any/all prompting
- **context.overrides.skipPromptParameters**: Skip stack parameter prompting, but not diff and/or changeset approvals.

**Comment by ingalls** [comment]
Hey Ryan, good to see your avatar again :) Yeah the problem I'm seeing is due to not passing the override to cloudformation to do the diff. It's very possible I'm misunderstanding the override system.

Essentially I'm mimicking the `mbx` behavior of automatically populating a CF Parameter Key called `GitSha`. I pass this variable into cfn-config via a key on the override object.

Previously:
- the override would be internally placed on the `oldParameters` object
- the user prompted, and generally accept the new overridden GitSha via the prompt
- the `GitSha` parameter on oldParam and newParam would be equal, but the value itself would still be passed to AWS CF.
- CF would detect the new gitsha, and update the stack.

The new behavior as far as I can tell is:
- the override would be internally placed on the `oldParameters` object
- the user prompted, and generally accept the new overridden GitSha via the prompt
- the `GitSha` parameter on oldParam and newParam would be equal and __no value would be passed__, instead the `UsePreviousValue=True` would be set.
- Since CF has been told to use the previous value, it would not detect any difference, and despite the user accepting a new GitSha, no update would be performed.

**Comment by rclark** [comment]
I get it -- so what's happening is that the overridden value gets set as both `.oldParameters` and `.newParameters`. This prevents the overridden variable in a parameter-value-approval prompt. But it also lines up the [`changesetParameters` function](https://github.com/mapbox/cfn-config/blob/65e11bff0ba1b749b8880090f28599fadb8778cc/lib/commands.js#L842-L855) to drop a `UsePreviousValue: true`. 

In the prior state, overridden parameters would be old and new, preventing unwanted approval, but we'd still pass the value to the changesets explicitly. Detection of what to send to the changeset needs to be made aware of any overridden value.
