### ISSUE TITLE
Do not require a call to IAM.getUser

### ISSUE THREAD

**Issue by freenerd** [mapbox/cfn-config#69]
In https://github.com/mapbox/cfn-config/blob/master/index.js#L438-L464 we have a call to IAM.getUser to retrieve the AccountID for building the bucket path to hold templates. This fails if the used credentials are not of a user but of an assumed role.

I suggest we either make the template-path or AccountID configureable or build this in a way that the AccountID is not needed at all.

/cc @rclark @willwhite

**Comment by camilleanne** [comment]
I've been hitting this pretty hard with the new roles for the mobile metrics stack -- I can't update the production stacks in an elevated role. Is @rclark's suggestion still a reasonable one?

cc @ianshward

**Comment by mick** [comment]
So we can keep this the same bucket structure that we already use, how about lets start by making the accountid configurable. Then or projects that use this lib can handle setting that config?

**Comment by ianshward** [comment]
@mick @rclark does this seem ok https://github.com/mapbox/cfn-config/pull/80 ?
