### ISSUE TITLE
Configure bucket for each region

### ISSUE THREAD

**Issue by willwhite** [mapbox/cfn-config#75]
cfn-config auto-creates it's own dedicated buckets - one for each region. This should be configurable so if you have existing buckets in each region you can use them instead. AWS limits the number of buckets on each account and this would help keep bucket sprawl at bay.

One option would be to keep the current behavior (auto-create bucket) as a default. But avoiding it entirely and forcing express configuration would greatly simplify the codebase and allow us to remove the [call to `iam.getUser()`](https://github.com/mapbox/cfn-config/blob/1df90c0e2e0088a2594e58632510c69bb282a75e/index.js#L438).

/cc @rclark @freenerd

**Comment by willwhite** [comment]
We should also consolidate buckets for where we stash the `cfn-configs` json files.

**Comment by rclark** [comment]
Let's make this required config and move ahead as described in #69
