### ISSUE TITLE
Add template validation

### ISSUE THREAD

**Issue by zmully** [mapbox/cfn-config#76]
nodejs aws-sdk as of 2.0.19 has CFN template validation:
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFormation.html#validateTemplate-property

**Comment by miccolis** [comment]
This API appears useless. I tested it out on a bad template and now I've got no idea WTF they mean by 'validate'. See https://gist.github.com/miccolis/70c9258b41cd34cb2590

@zmully I think the next step is to push back on support.

**Comment by zmully** [comment]
https://console.aws.amazon.com/support/home?region=us-east-1#/case/?displayId=1507023181&language=en

Basically, they've thought about it, but no timeframe on when they'll deliver something useful.
