### ISSUE TITLE
`./` in -t path causes S3 configs to not be found

### ISSUE THREAD

**Issue by ianshward** [mapbox/cfn-config#89]
`./path/to/template` does not work to load cfn configurations in S3, whereas `path/to/template` does.  Issue is in https://github.com/mapbox/cfn-config/blob/327506da0a721c4061b71ae83984b41a0b579dc8/index.js#L531 Thanks @Rub21 for debugging this.

The solution might look like detecting leading `./` and removing it / otherwise handling it.

**Comment by Rub21** [comment]
I have made some improvement [here on PR](https://github.com/mapbox/cfn-config/pull/90) to resolve this error.

**Comment by Rub21** [comment]
Good progress here, the changes was publish in NPM and [repository tag-0.8.4](https://github.com/mapbox/cfn-config/tree/v0.8.4)
